"""Email attendance reports to faculty via Flask-Mail."""
from flask_mail import Message
from app.extensions import mail
from app.services.export_service import export_to_excel


def email_attendance_report(recipients: list[str], records, subject: str = "Attendance Report") -> None:
    if not recipients:
        raise ValueError("No recipient email addresses provided.")

    excel_buf = export_to_excel(records)
    msg = Message(
        subject=subject,
        recipients=recipients,
        body=(
            "Please find attached the attendance report generated by the "
            "Smart Attendance Monitoring System."
        ),
    )
    msg.attach(
        filename="attendance_report.xlsx",
        content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        data=excel_buf.read(),
    )
    mail.send(msg)
